name: ThirdGlance
favicon: null
layout_spectrum: 0.2347
typography_spectrum: 0.28263
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2fae3'
    - '#070604'
    - '#d8ce9d'
    - '#77532f'
    - '#ae9263'
  brandStrength: 0.75
  lightness: 0.25120379170402884
  saturation: 0.26692668651230633
  rhythmicContrast: 0.5356916026212275
purpose: []
