name: ThirdGlance
favicon: null
layout_spectrum: 0.38692025281488895
typography_spectrum: 0.2961192156653851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9635702499654144
  lightness: 0.25120379170402884
  saturation: 0.26692668651230633
  rhythmicContrast: 0.5356916026212275
purpose: []
